language: ruby
branches:
  only:
  - master
rvm:
  - 2.3
  - 2.4.4
  - 2.5
# - 2.6 # Removing for now due to: https://github.com/rubocop-hq/rubocop/pull/6413
before_install:
  - gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rake
