Vagrant.configure('2') do |config|
  config.vm.box = 'bento/ubuntu-18.04'

  config.vm.network 'forwarded_port', guest: 22, host: 7022, host_ip: '127.0.0.1'
  config.vm.network 'forwarded_port', guest: 80, host: 7080, host_ip: '127.0.0.1'
  config.vm.network 'forwarded_port', guest: 9631, host: 7631, host_ip: '127.0.0.1'

  config.vm.provision 'shell', path: 'bootstrap.sh'
end
